<?php
// Fonte única de verdade: rota da SPA => [ficheiro em app/pages/, título].
// Usado por public/view.php (whitelist), public/index.php (envia ao JS) e app.js (regista as rotas).
return [
    '/'                     => ['index.php',                'Dashboard'],
    '/contacts'             => ['contacts.php',             'Clientes/Empresas'],
    '/contacts/create'      => ['contacts.php',             'Clientes/Empresas'],
    '/items'                => ['items.php',                'Produtos/Serviços'],
    '/invoices'             => ['list_invoices.php',        'Faturas'],
    '/invoices/create'      => ['create_invoices.php',      'Nova fatura'],
    '/invoices/view'        => ['invoice.php',              'Fatura'],
    '/proformas'            => ['list_proforms.php',        'Proformas'],
    '/proformas/create'     => ['create_proform.php',       'Nova proforma'],
    '/proformas/view'       => ['proform.php',              'Proforma'],
    '/credit-note'          => ['credit_note.php',          'Nota de crédito'],
    '/stock'                => ['stock.php',                'Stock'],
    '/stock/view'           => ['stock_view.php',           'Stock'],
    '/guides'               => ['guides.php',               'Guias'],
    '/guides/list'          => ['list_guides.php',          'Guias'],
    '/guides/view'          => ['view_guide.php',           'Guia'],
    '/subscription'         => ['subscription.php',         'Subscrição'],
    '/companies'            => ['list_companies.php',       'Empresas'],
    '/companies/edit'       => ['edit_company.php',         'Editar empresa'],
    '/users'                => ['manage_users.php',         'Utilizadores'],
    '/profile'              => ['perfil.php',               'Perfil'],
    '/notificacoes'         => ['notificacoes.php',         'Notificações'],
    '/insights'             => ['insights.php',             'Insights'],
    '/intelligence'         => ['intelligence.php',         'Inteligência'],
    '/customer-intelligence'=> ['customer_intelligence.php','Inteligência de clientes'],
    '/ai-actions'           => ['ai_actions.php',           'Ações IA'],
    '/help'                 => ['help.php',                 'Ajuda'],
    // Recursos Humanos
    '/rh'                   => ['rh_dashboard.php',         'RH'],
    '/employees'            => ['employees.php',            'Funcionários'],
    '/departments'          => ['departments.php',          'Departamentos'],
    '/positions'            => ['positions.php',            'Cargos'],
    '/organograma'          => ['organograma.php',          'Organograma'],
    '/payroll'              => ['payroll.php',              'Folha salarial'],
    '/ponto'                => ['ponto.php',                'Ponto'],
    '/vacations'            => ['vacations.php',            'Férias'],
    '/avaliacoes'           => ['avaliacoes.php',           'Avaliações'],
    '/settings'             => ['list_companies.php',       'Definições'],
];
